// <auto-generated />
using AnimeBookmarksV2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeBookmarksV2.Migrations
{
    [DbContext(typeof(AnimeDbContext))]
    [Migration("20250423142450_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimeBookmarksV2.Models.AnimeGenre", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("AnimeId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("AnimeGenres");

                    b.HasData(
                        new
                        {
                            AnimeId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            AnimeId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            AnimeId = 1,
                            GenreId = 3
                        },
                        new
                        {
                            AnimeId = 1,
                            GenreId = 5
                        },
                        new
                        {
                            AnimeId = 2,
                            GenreId = 7
                        },
                        new
                        {
                            AnimeId = 2,
                            GenreId = 4
                        },
                        new
                        {
                            AnimeId = 3,
                            GenreId = 3
                        },
                        new
                        {
                            AnimeId = 3,
                            GenreId = 4
                        },
                        new
                        {
                            AnimeId = 3,
                            GenreId = 5
                        },
                        new
                        {
                            AnimeId = 3,
                            GenreId = 6
                        },
                        new
                        {
                            AnimeId = 4,
                            GenreId = 1
                        },
                        new
                        {
                            AnimeId = 4,
                            GenreId = 2
                        },
                        new
                        {
                            AnimeId = 4,
                            GenreId = 5
                        });
                });

            modelBuilder.Entity("AnimeBookmarksV2.Models.Animev2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnimeLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Anime");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimeLink = "https://www.crunchyroll.com/series/G649PJ0JY/blue-exorcist",
                            Description = "The story revolves around Rin Okumura, a teenager who discovers that he and his twin brother Yukio are the sons of Satan, born from a human woman, and he is the inheritor of Satan's powers.",
                            ImagePath = "/AnimeImages/s-l1200.jpg",
                            Title = "Blue Exorcist"
                        },
                        new
                        {
                            Id = 2,
                            AnimeLink = "https://www.crunchyroll.com/series/G4PH0WEKE/blue-lock",
                            Description = " Three hundred high school players are pitted against each other for the position, but only one will come out on top. Who among them will be the striker to usher in a new era of Japanese soccer?",
                            ImagePath = "/AnimeImages/blueLock.jpg",
                            Title = "BLUE LOCK"
                        },
                        new
                        {
                            Id = 3,
                            AnimeLink = "https://www.crunchyroll.com/series/G63VMKVQY/yamada-kun-and-the-seven-witches",
                            Description = "Suzaku High School student and problem kid, Ryu Yamada, is in a bad mood after being chewed out again by the teacher today. As if his day couldn’t get any worse, he falls down the top of the stairs with honor student, Urara Shiraishi! When he comes to, he’s switched bodies with her!",
                            ImagePath = "/AnimeImages/sevenWitches.jpg",
                            Title = "Yamada-kun and the Seven Witches"
                        },
                        new
                        {
                            Id = 4,
                            AnimeLink = "https://www.crunchyroll.com/series/GYZJ43JMR/that-time-i-got-reincarnated-as-a-slime",
                            Description = "Corporate worker Mikami Satoru is stabbed by a random killer, and is reborn to an alternate world. But he turns out to be reborn a slime!\r\nThrown into this new world with the name Rimuru, he begins his quest to create a world that’s welcoming to all races.",
                            ImagePath = "/AnimeImages/reincarnationAsASlime.jpg",
                            Title = "That Time I Got Reincarnation as a Slime"
                        });
                });

            modelBuilder.Entity("AnimeBookmarksV2.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sports"
                        });
                });

            modelBuilder.Entity("AnimeBookmarksV2.Models.UserAccounts", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            Email = "admin@email.com",
                            Password = "password123",
                            Role = "Admin",
                            Username = "Admin_Creator"
                        },
                        new
                        {
                            AccountId = 2,
                            Email = "guest@email.com",
                            Password = "password123",
                            Role = "User",
                            Username = "Guest"
                        });
                });

            modelBuilder.Entity("AnimeBookmarksV2.Models.UserBookmarks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("AnimeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AnimeId");

                    b.ToTable("Bookmarks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            AnimeId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 1,
                            AnimeId = 4
                        });
                });

            modelBuilder.Entity("AnimeBookmarksV2.Models.AnimeGenre", b =>
                {
                    b.HasOne("AnimeBookmarksV2.Models.Animev2", "Anime")
                        .WithMany("AnimeGenres")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeBookmarksV2.Models.Genre", "Genre")
                        .WithMany("AnimeGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AnimeBookmarksV2.Models.UserBookmarks", b =>
                {
                    b.HasOne("AnimeBookmarksV2.Models.UserAccounts", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeBookmarksV2.Models.Animev2", "Anime")
                        .WithMany()
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimeBookmarksV2.Models.Animev2", b =>
                {
                    b.Navigation("AnimeGenres");
                });

            modelBuilder.Entity("AnimeBookmarksV2.Models.Genre", b =>
                {
                    b.Navigation("AnimeGenres");
                });

            modelBuilder.Entity("AnimeBookmarksV2.Models.UserAccounts", b =>
                {
                    b.Navigation("Bookmarks");
                });
#pragma warning restore 612, 618
        }
    }
}
