<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\photoOfself\5997CA50-3728-407F-A06C-EC64D3A96DA2resize.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="bootstrap" Version="5.3.3" />
  </ItemGroup>

</Project>
