// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_6_1.Models;

#nullable disable

namespace Project_6_1.Migrations
{
    [DbContext(typeof(QuestionContext))]
    [Migration("20250206174015_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_6_1.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryType = "General"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryType = "History"
                        });
                });

            modelBuilder.Entity("Project_6_1.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TopicId");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            QuestionId = 1,
                            CategoryId = 1,
                            QuestionText = "What is Bootstrap?",
                            Response = "A CSS framework for creating responsive web apps for multiple screen sizes.",
                            TopicId = 1
                        },
                        new
                        {
                            QuestionId = 2,
                            CategoryId = 1,
                            QuestionText = "What is C#?",
                            Response = "A general purpose object-oriented language that uses a concise, Java-like syntax.",
                            TopicId = 2
                        },
                        new
                        {
                            QuestionId = 3,
                            CategoryId = 1,
                            QuestionText = "What is JavaScript?",
                            Response = "A general purpose scripting language that executes in a web browser.",
                            TopicId = 3
                        },
                        new
                        {
                            QuestionId = 4,
                            CategoryId = 2,
                            QuestionText = "When was Bootstrap first released?",
                            Response = "In 2011.",
                            TopicId = 1
                        },
                        new
                        {
                            QuestionId = 5,
                            CategoryId = 2,
                            QuestionText = "When was C# first released?",
                            Response = "In 2002.",
                            TopicId = 2
                        });
                });

            modelBuilder.Entity("Project_6_1.Models.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopicId"));

                    b.Property<string>("TheTopic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            TopicId = 1,
                            TheTopic = "Bootstrap"
                        },
                        new
                        {
                            TopicId = 2,
                            TheTopic = "C#"
                        },
                        new
                        {
                            TopicId = 3,
                            TheTopic = "JavaScript"
                        });
                });

            modelBuilder.Entity("Project_6_1.Models.Question", b =>
                {
                    b.HasOne("Project_6_1.Models.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_6_1.Models.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Project_6_1.Models.Category", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Project_6_1.Models.Topic", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
