// <auto-generated />
using GiftCardsShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GiftCardsShop.Migrations
{
    [DbContext(typeof(GiftCardDbContext))]
    [Migration("20250302211300_AddedCarts")]
    partial class AddedCarts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GiftCardsShop.Models.CartItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GiftCardId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GiftCardId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("GiftCardsShop.Models.GiftCards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fortnite V Bucks used to buy cosmetics from the item shop",
                            Img = "",
                            Name = "Fortnite 1000 V-Bucks",
                            Price = 8.9900000000000002,
                            Slug = "fortnite-v-bucks"
                        },
                        new
                        {
                            Id = 2,
                            Description = "PS Gift Card used to make purchases on PS Store",
                            Img = "",
                            Name = "PS 25$ Gift Card",
                            Price = 25.0,
                            Slug = "ps-gift-card"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Enhance your PlayStation experience with core features, including online multiplayer access, monthly games, exclusive discounts, and more.",
                            Img = "",
                            Name = "PS Plus Essential 12 Month Subscription",
                            Price = 79.989999999999995,
                            Slug = "ps-plus"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Give the gift of delivery with a DoorDash gift card. The DoorDash app connects your favorite people with the best of their neighborhood.",
                            Img = "",
                            Name = "DoorDash 50$ Gift Card",
                            Price = 50.0,
                            Slug = "doordash-gift-card"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Roblox, Roblox Gift Card",
                            Img = "",
                            Name = "Roblox $25 Gift Card",
                            Price = 25.0,
                            Slug = "roblox-gift-card"
                        });
                });

            modelBuilder.Entity("GiftCardsShop.Models.CartItems", b =>
                {
                    b.HasOne("GiftCardsShop.Models.GiftCards", "GiftCard")
                        .WithMany()
                        .HasForeignKey("GiftCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiftCard");
                });
#pragma warning restore 612, 618
        }
    }
}
